version: '3'
services:
    web:
        container_name: nginx-resta
        image: nginx:latest
        restart: always
        ports:
        - "80:80"
        volumes:
        - .:/var/www/html/app
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    redis:
        container_name: redis-resta
        image: redis
        restart: always
        ports:
        - "6379:6379"
        networks:
          default:
            ipv4_address: 172.10.0.6
    mysql:
        container_name: mysql-resta
        image: mysql:5.7
        ports:
        - "33061:3306"
        - "3306:3306"
        volumes:
        - ./docker/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: resta
        networks:
          default:
            ipv4_address: 172.10.0.5
    php:
        container_name: php-resta
        build: docker
        image: php:fpm
        restart: always
        volumes:
        - .:/var/www/html/app
networks:
  default:
      driver: bridge
      ipam:
        config:
            - subnet: 172.10.0.0/24

