version: '3'
services:
    web:
        container_name: nginx
        image: nginx:latest
        ports:
        - "80:80"
        volumes:
        - .:/var/www/html/app
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    redis:
        container_name: redis
        image: redis
        ports:
        - "6379:6379"
    mysql:
        container_name: mysql
        image: mysql
        ports:
        - "33061:3306"
        - "3306:3306"
        volumes:
        - ./docker/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
    php:
        container_name: php
        build: docker
        image: php:fpm
        volumes:
        - .:/var/www/html/app
networks:
  default:
      driver: bridge
      ipam:
        config:
            - subnet: 172.10.0.0/24

